// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConntrackExportHandlerFunc turns a function with the right signature into a get conntrack export handler
type GetConntrackExportHandlerFunc func(GetConntrackExportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConntrackExportHandlerFunc) Handle(params GetConntrackExportParams) middleware.Responder {
	return fn(params)
}

// GetConntrackExportHandler interface for that can handle valid get conntrack export params
type GetConntrackExportHandler interface {
	Handle(GetConntrackExportParams) middleware.Responder
}

// NewGetConntrackExport creates a new http.Handler for the get conntrack export operation
func NewGetConntrackExport(ctx *middleware.Context, handler GetConntrackExportHandler) *GetConntrackExport {
	return &GetConntrackExport{Context: ctx, Handler: handler}
}

/*
	GetConntrackExport swagger:route GET /conntrack/export daemon getConntrackExport

Export conntrack entries for an IPv4 endpoint
*/
type GetConntrackExport struct {
	Context *middleware.Context
	Handler GetConntrackExportHandler
}

func (o *GetConntrackExport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConntrackExportParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
