// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/cilium/api/v1/models"
)

// GetIncOKCode is the HTTP code returned for type GetIncOK
const GetIncOKCode int = 200

/*
GetIncOK Success

swagger:response getIncOK
*/
type GetIncOK struct {

	/*
	  In: Body
	*/
	Payload *models.IncResponse `json:"body,omitempty"`
}

// NewGetIncOK creates GetIncOK with default headers values
func NewGetIncOK() *GetIncOK {

	return &GetIncOK{}
}

// WithPayload adds the payload to the get inc o k response
func (o *GetIncOK) WithPayload(payload *models.IncResponse) *GetIncOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get inc o k response
func (o *GetIncOK) SetPayload(payload *models.IncResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetIncOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
