// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetConntrackExportParams creates a new GetConntrackExportParams object
//
// There are no default values defined in the spec.
func NewGetConntrackExportParams() GetConntrackExportParams {

	return GetConntrackExportParams{}
}

// GetConntrackExportParams contains all the bound params for the get conntrack export operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetConntrackExport
type GetConntrackExportParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*IPv4 address of the endpoint
	  Required: true
	  Pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
	  In: query
	*/
	Ip4 string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetConntrackExportParams() beforehand.
func (o *GetConntrackExportParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qIp4, qhkIp4, _ := qs.GetOK("ip4")
	if err := o.bindIp4(qIp4, qhkIp4, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIp4 binds and validates parameter Ip4 from query.
func (o *GetConntrackExportParams) bindIp4(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("ip4", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("ip4", "query", raw); err != nil {
		return err
	}
	o.Ip4 = raw

	if err := o.validateIp4(formats); err != nil {
		return err
	}

	return nil
}

// validateIp4 carries on validations for parameter Ip4
func (o *GetConntrackExportParams) validateIp4(formats strfmt.Registry) error {

	if err := validate.Pattern("ip4", "query", o.Ip4, `^([0-9]{1,3}\.){3}[0-9]{1,3}$`); err != nil {
		return err
	}

	return nil
}
