// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetConntrackExportOKCode is the HTTP code returned for type GetConntrackExportOK
const GetConntrackExportOKCode int = 200

/*
GetConntrackExportOK NDJSON stream of conntrack entries

swagger:response getConntrackExportOK
*/
type GetConntrackExportOK struct {
}

// NewGetConntrackExportOK creates GetConntrackExportOK with default headers values
func NewGetConntrackExportOK() *GetConntrackExportOK {

	return &GetConntrackExportOK{}
}

// WriteResponse to the client
func (o *GetConntrackExportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
