// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetIncHandlerFunc turns a function with the right signature into a get inc handler
type GetIncHandlerFunc func(GetIncParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIncHandlerFunc) Handle(params GetIncParams) middleware.Responder {
	return fn(params)
}

// GetIncHandler interface for that can handle valid get inc params
type GetIncHandler interface {
	Handle(GetIncParams) middleware.Responder
}

// NewGetInc creates a new http.Handler for the get inc operation
func NewGetInc(ctx *middleware.Context, handler GetIncHandler) *GetInc {
	return &GetInc{Context: ctx, Handler: handler}
}

/*
	GetInc swagger:route GET /inc daemon getInc

Increment a number by 1
*/
type GetInc struct {
	Context *middleware.Context
	Handler GetIncHandler
}

func (o *GetInc) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetIncParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
