// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetIncParams creates a new GetIncParams object
//
// There are no default values defined in the spec.
func NewGetIncParams() GetIncParams {

	return GetIncParams{}
}

// GetIncParams contains all the bound params for the get inc operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetInc
type GetIncParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Number to increment
	  Required: true
	  In: query
	*/
	X int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetIncParams() beforehand.
func (o *GetIncParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qX, qhkX, _ := qs.GetOK("x")
	if err := o.bindX(qX, qhkX, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindX binds and validates parameter X from query.
func (o *GetIncParams) bindX(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("x", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("x", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("x", "query", "int64", raw)
	}
	o.X = value

	return nil
}
