// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostConntrackImportOKCode is the HTTP code returned for type PostConntrackImportOK
const PostConntrackImportOKCode int = 200

/*
PostConntrackImportOK OK

swagger:response postConntrackImportOK
*/
type PostConntrackImportOK struct {
}

// NewPostConntrackImportOK creates PostConntrackImportOK with default headers values
func NewPostConntrackImportOK() *PostConntrackImportOK {

	return &PostConntrackImportOK{}
}

// WriteResponse to the client
func (o *PostConntrackImportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostConntrackImportBadRequestCode is the HTTP code returned for type PostConntrackImportBadRequest
const PostConntrackImportBadRequestCode int = 400

/*
PostConntrackImportBadRequest Invalid or unsupported conntrack export version.
The value of the Cilium-Conntrack-Export-Version header does not
match any version supported by this cilium agent.

swagger:response postConntrackImportBadRequest
*/
type PostConntrackImportBadRequest struct {
}

// NewPostConntrackImportBadRequest creates PostConntrackImportBadRequest with default headers values
func NewPostConntrackImportBadRequest() *PostConntrackImportBadRequest {

	return &PostConntrackImportBadRequest{}
}

// WriteResponse to the client
func (o *PostConntrackImportBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostConntrackImportInternalServerErrorCode is the HTTP code returned for type PostConntrackImportInternalServerError
const PostConntrackImportInternalServerErrorCode int = 500

/*
PostConntrackImportInternalServerError Internal server error. Failed to allocate or initialize conntrack
batch contexts, or another server-side error occurred while processing
the import.

swagger:response postConntrackImportInternalServerError
*/
type PostConntrackImportInternalServerError struct {
}

// NewPostConntrackImportInternalServerError creates PostConntrackImportInternalServerError with default headers values
func NewPostConntrackImportInternalServerError() *PostConntrackImportInternalServerError {

	return &PostConntrackImportInternalServerError{}
}

// WriteResponse to the client
func (o *PostConntrackImportInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
