// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostConntrackImportOKCode is the HTTP code returned for type PostConntrackImportOK
const PostConntrackImportOKCode int = 200

/*
PostConntrackImportOK OK

swagger:response postConntrackImportOK
*/
type PostConntrackImportOK struct {
}

// NewPostConntrackImportOK creates PostConntrackImportOK with default headers values
func NewPostConntrackImportOK() *PostConntrackImportOK {

	return &PostConntrackImportOK{}
}

// WriteResponse to the client
func (o *PostConntrackImportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
