// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConntrackImportHandlerFunc turns a function with the right signature into a post conntrack import handler
type PostConntrackImportHandlerFunc func(PostConntrackImportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConntrackImportHandlerFunc) Handle(params PostConntrackImportParams) middleware.Responder {
	return fn(params)
}

// PostConntrackImportHandler interface for that can handle valid post conntrack import params
type PostConntrackImportHandler interface {
	Handle(PostConntrackImportParams) middleware.Responder
}

// NewPostConntrackImport creates a new http.Handler for the post conntrack import operation
func NewPostConntrackImport(ctx *middleware.Context, handler PostConntrackImportHandler) *PostConntrackImport {
	return &PostConntrackImport{Context: ctx, Handler: handler}
}

/*
	PostConntrackImport swagger:route POST /conntrack/import daemon postConntrackImport

Import conntrack entries as plain binary stream
*/
type PostConntrackImport struct {
	Context *middleware.Context
	Handler PostConntrackImportHandler
}

func (o *PostConntrackImport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConntrackImportParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
