// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewPostConntrackImportParams creates a new PostConntrackImportParams object
//
// There are no default values defined in the spec.
func NewPostConntrackImportParams() PostConntrackImportParams {

	return PostConntrackImportParams{}
}

// PostConntrackImportParams contains all the bound params for the post conntrack import operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostConntrackImport
type PostConntrackImportParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Conntrack binary export format version
	  Required: true
	  In: header
	*/
	CiliumConntrackExportVersion string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConntrackImportParams() beforehand.
func (o *PostConntrackImportParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindCiliumConntrackExportVersion(r.Header[http.CanonicalHeaderKey("Cilium-Conntrack-Export-Version")], true, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCiliumConntrackExportVersion binds and validates parameter CiliumConntrackExportVersion from header.
func (o *PostConntrackImportParams) bindCiliumConntrackExportVersion(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Cilium-Conntrack-Export-Version", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Cilium-Conntrack-Export-Version", "header", raw); err != nil {
		return err
	}
	o.CiliumConntrackExportVersion = raw

	return nil
}
