// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetConntrackExportReader is a Reader for the GetConntrackExport structure.
type GetConntrackExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConntrackExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConntrackExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /conntrack/export] GetConntrackExport", response, response.Code())
	}
}

// NewGetConntrackExportOK creates a GetConntrackExportOK with default headers values
func NewGetConntrackExportOK() *GetConntrackExportOK {
	return &GetConntrackExportOK{}
}

/*
GetConntrackExportOK describes a response with status code 200, with default header values.

NDJSON stream of conntrack entries
*/
type GetConntrackExportOK struct {
}

// IsSuccess returns true when this get conntrack export o k response has a 2xx status code
func (o *GetConntrackExportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get conntrack export o k response has a 3xx status code
func (o *GetConntrackExportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get conntrack export o k response has a 4xx status code
func (o *GetConntrackExportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get conntrack export o k response has a 5xx status code
func (o *GetConntrackExportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get conntrack export o k response a status code equal to that given
func (o *GetConntrackExportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get conntrack export o k response
func (o *GetConntrackExportOK) Code() int {
	return 200
}

func (o *GetConntrackExportOK) Error() string {
	return fmt.Sprintf("[GET /conntrack/export][%d] getConntrackExportOK", 200)
}

func (o *GetConntrackExportOK) String() string {
	return fmt.Sprintf("[GET /conntrack/export][%d] getConntrackExportOK", 200)
}

func (o *GetConntrackExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
