// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetIncParams creates a new GetIncParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIncParams() *GetIncParams {
	return &GetIncParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIncParamsWithTimeout creates a new GetIncParams object
// with the ability to set a timeout on a request.
func NewGetIncParamsWithTimeout(timeout time.Duration) *GetIncParams {
	return &GetIncParams{
		timeout: timeout,
	}
}

// NewGetIncParamsWithContext creates a new GetIncParams object
// with the ability to set a context for a request.
func NewGetIncParamsWithContext(ctx context.Context) *GetIncParams {
	return &GetIncParams{
		Context: ctx,
	}
}

// NewGetIncParamsWithHTTPClient creates a new GetIncParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIncParamsWithHTTPClient(client *http.Client) *GetIncParams {
	return &GetIncParams{
		HTTPClient: client,
	}
}

/*
GetIncParams contains all the parameters to send to the API endpoint

	for the get inc operation.

	Typically these are written to a http.Request.
*/
type GetIncParams struct {

	/* X.

	   Number to increment
	*/
	X int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inc params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIncParams) WithDefaults() *GetIncParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inc params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIncParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inc params
func (o *GetIncParams) WithTimeout(timeout time.Duration) *GetIncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inc params
func (o *GetIncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inc params
func (o *GetIncParams) WithContext(ctx context.Context) *GetIncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inc params
func (o *GetIncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inc params
func (o *GetIncParams) WithHTTPClient(client *http.Client) *GetIncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inc params
func (o *GetIncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithX adds the x to the get inc params
func (o *GetIncParams) WithX(x int64) *GetIncParams {
	o.SetX(x)
	return o
}

// SetX adds the x to the get inc params
func (o *GetIncParams) SetX(x int64) {
	o.X = x
}

// WriteToRequest writes these params to a swagger request
func (o *GetIncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param x
	qrX := o.X
	qX := swag.FormatInt64(qrX)
	if qX != "" {

		if err := r.SetQueryParam("x", qX); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
