// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConntrackExportParams creates a new GetConntrackExportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetConntrackExportParams() *GetConntrackExportParams {
	return &GetConntrackExportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetConntrackExportParamsWithTimeout creates a new GetConntrackExportParams object
// with the ability to set a timeout on a request.
func NewGetConntrackExportParamsWithTimeout(timeout time.Duration) *GetConntrackExportParams {
	return &GetConntrackExportParams{
		timeout: timeout,
	}
}

// NewGetConntrackExportParamsWithContext creates a new GetConntrackExportParams object
// with the ability to set a context for a request.
func NewGetConntrackExportParamsWithContext(ctx context.Context) *GetConntrackExportParams {
	return &GetConntrackExportParams{
		Context: ctx,
	}
}

// NewGetConntrackExportParamsWithHTTPClient creates a new GetConntrackExportParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetConntrackExportParamsWithHTTPClient(client *http.Client) *GetConntrackExportParams {
	return &GetConntrackExportParams{
		HTTPClient: client,
	}
}

/*
GetConntrackExportParams contains all the parameters to send to the API endpoint

	for the get conntrack export operation.

	Typically these are written to a http.Request.
*/
type GetConntrackExportParams struct {

	/* Ip4.

	   IPv4 address of the endpoint
	*/
	Ip4 string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get conntrack export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConntrackExportParams) WithDefaults() *GetConntrackExportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get conntrack export params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConntrackExportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get conntrack export params
func (o *GetConntrackExportParams) WithTimeout(timeout time.Duration) *GetConntrackExportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get conntrack export params
func (o *GetConntrackExportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get conntrack export params
func (o *GetConntrackExportParams) WithContext(ctx context.Context) *GetConntrackExportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get conntrack export params
func (o *GetConntrackExportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get conntrack export params
func (o *GetConntrackExportParams) WithHTTPClient(client *http.Client) *GetConntrackExportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get conntrack export params
func (o *GetConntrackExportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIp4 adds the ip4 to the get conntrack export params
func (o *GetConntrackExportParams) WithIp4(ip4 string) *GetConntrackExportParams {
	o.SetIp4(ip4)
	return o
}

// SetIp4 adds the ip4 to the get conntrack export params
func (o *GetConntrackExportParams) SetIp4(ip4 string) {
	o.Ip4 = ip4
}

// WriteToRequest writes these params to a swagger request
func (o *GetConntrackExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param ip4
	qrIp4 := o.Ip4
	qIp4 := qrIp4
	if qIp4 != "" {

		if err := r.SetQueryParam("ip4", qIp4); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
