// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cilium/cilium/api/v1/models"
)

// GetIncReader is a Reader for the GetInc structure.
type GetIncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /inc] GetInc", response, response.Code())
	}
}

// NewGetIncOK creates a GetIncOK with default headers values
func NewGetIncOK() *GetIncOK {
	return &GetIncOK{}
}

/*
GetIncOK describes a response with status code 200, with default header values.

Success
*/
type GetIncOK struct {
	Payload *models.IncResponse
}

// IsSuccess returns true when this get inc o k response has a 2xx status code
func (o *GetIncOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get inc o k response has a 3xx status code
func (o *GetIncOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get inc o k response has a 4xx status code
func (o *GetIncOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get inc o k response has a 5xx status code
func (o *GetIncOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get inc o k response a status code equal to that given
func (o *GetIncOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get inc o k response
func (o *GetIncOK) Code() int {
	return 200
}

func (o *GetIncOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /inc][%d] getIncOK %s", 200, payload)
}

func (o *GetIncOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /inc][%d] getIncOK %s", 200, payload)
}

func (o *GetIncOK) GetPayload() *models.IncResponse {
	return o.Payload
}

func (o *GetIncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IncResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
