// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostConntrackImportParams creates a new PostConntrackImportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostConntrackImportParams() *PostConntrackImportParams {
	return &PostConntrackImportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostConntrackImportParamsWithTimeout creates a new PostConntrackImportParams object
// with the ability to set a timeout on a request.
func NewPostConntrackImportParamsWithTimeout(timeout time.Duration) *PostConntrackImportParams {
	return &PostConntrackImportParams{
		timeout: timeout,
	}
}

// NewPostConntrackImportParamsWithContext creates a new PostConntrackImportParams object
// with the ability to set a context for a request.
func NewPostConntrackImportParamsWithContext(ctx context.Context) *PostConntrackImportParams {
	return &PostConntrackImportParams{
		Context: ctx,
	}
}

// NewPostConntrackImportParamsWithHTTPClient creates a new PostConntrackImportParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostConntrackImportParamsWithHTTPClient(client *http.Client) *PostConntrackImportParams {
	return &PostConntrackImportParams{
		HTTPClient: client,
	}
}

/*
PostConntrackImportParams contains all the parameters to send to the API endpoint

	for the post conntrack import operation.

	Typically these are written to a http.Request.
*/
type PostConntrackImportParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post conntrack import params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostConntrackImportParams) WithDefaults() *PostConntrackImportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post conntrack import params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostConntrackImportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post conntrack import params
func (o *PostConntrackImportParams) WithTimeout(timeout time.Duration) *PostConntrackImportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post conntrack import params
func (o *PostConntrackImportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post conntrack import params
func (o *PostConntrackImportParams) WithContext(ctx context.Context) *PostConntrackImportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post conntrack import params
func (o *PostConntrackImportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post conntrack import params
func (o *PostConntrackImportParams) WithHTTPClient(client *http.Client) *PostConntrackImportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post conntrack import params
func (o *PostConntrackImportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostConntrackImportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
