// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostConntrackImportReader is a Reader for the PostConntrackImport structure.
type PostConntrackImportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostConntrackImportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostConntrackImportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostConntrackImportBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostConntrackImportInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /conntrack/import] PostConntrackImport", response, response.Code())
	}
}

// NewPostConntrackImportOK creates a PostConntrackImportOK with default headers values
func NewPostConntrackImportOK() *PostConntrackImportOK {
	return &PostConntrackImportOK{}
}

/*
PostConntrackImportOK describes a response with status code 200, with default header values.

OK
*/
type PostConntrackImportOK struct {
}

// IsSuccess returns true when this post conntrack import o k response has a 2xx status code
func (o *PostConntrackImportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post conntrack import o k response has a 3xx status code
func (o *PostConntrackImportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post conntrack import o k response has a 4xx status code
func (o *PostConntrackImportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post conntrack import o k response has a 5xx status code
func (o *PostConntrackImportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post conntrack import o k response a status code equal to that given
func (o *PostConntrackImportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post conntrack import o k response
func (o *PostConntrackImportOK) Code() int {
	return 200
}

func (o *PostConntrackImportOK) Error() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportOK", 200)
}

func (o *PostConntrackImportOK) String() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportOK", 200)
}

func (o *PostConntrackImportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostConntrackImportBadRequest creates a PostConntrackImportBadRequest with default headers values
func NewPostConntrackImportBadRequest() *PostConntrackImportBadRequest {
	return &PostConntrackImportBadRequest{}
}

/*
	PostConntrackImportBadRequest describes a response with status code 400, with default header values.

	Invalid or unsupported conntrack export version.

The value of the Cilium-Conntrack-Export-Version header does not
match any version supported by this cilium agent.
*/
type PostConntrackImportBadRequest struct {
}

// IsSuccess returns true when this post conntrack import bad request response has a 2xx status code
func (o *PostConntrackImportBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post conntrack import bad request response has a 3xx status code
func (o *PostConntrackImportBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post conntrack import bad request response has a 4xx status code
func (o *PostConntrackImportBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post conntrack import bad request response has a 5xx status code
func (o *PostConntrackImportBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post conntrack import bad request response a status code equal to that given
func (o *PostConntrackImportBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post conntrack import bad request response
func (o *PostConntrackImportBadRequest) Code() int {
	return 400
}

func (o *PostConntrackImportBadRequest) Error() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportBadRequest", 400)
}

func (o *PostConntrackImportBadRequest) String() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportBadRequest", 400)
}

func (o *PostConntrackImportBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostConntrackImportInternalServerError creates a PostConntrackImportInternalServerError with default headers values
func NewPostConntrackImportInternalServerError() *PostConntrackImportInternalServerError {
	return &PostConntrackImportInternalServerError{}
}

/*
	PostConntrackImportInternalServerError describes a response with status code 500, with default header values.

	Internal server error. Failed to allocate or initialize conntrack

batch contexts, or another server-side error occurred while processing
the import.
*/
type PostConntrackImportInternalServerError struct {
}

// IsSuccess returns true when this post conntrack import internal server error response has a 2xx status code
func (o *PostConntrackImportInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post conntrack import internal server error response has a 3xx status code
func (o *PostConntrackImportInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post conntrack import internal server error response has a 4xx status code
func (o *PostConntrackImportInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post conntrack import internal server error response has a 5xx status code
func (o *PostConntrackImportInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post conntrack import internal server error response a status code equal to that given
func (o *PostConntrackImportInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post conntrack import internal server error response
func (o *PostConntrackImportInternalServerError) Code() int {
	return 500
}

func (o *PostConntrackImportInternalServerError) Error() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportInternalServerError", 500)
}

func (o *PostConntrackImportInternalServerError) String() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportInternalServerError", 500)
}

func (o *PostConntrackImportInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
