// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostConntrackImportReader is a Reader for the PostConntrackImport structure.
type PostConntrackImportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostConntrackImportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostConntrackImportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /conntrack/import] PostConntrackImport", response, response.Code())
	}
}

// NewPostConntrackImportOK creates a PostConntrackImportOK with default headers values
func NewPostConntrackImportOK() *PostConntrackImportOK {
	return &PostConntrackImportOK{}
}

/*
PostConntrackImportOK describes a response with status code 200, with default header values.

OK
*/
type PostConntrackImportOK struct {
}

// IsSuccess returns true when this post conntrack import o k response has a 2xx status code
func (o *PostConntrackImportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post conntrack import o k response has a 3xx status code
func (o *PostConntrackImportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post conntrack import o k response has a 4xx status code
func (o *PostConntrackImportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post conntrack import o k response has a 5xx status code
func (o *PostConntrackImportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post conntrack import o k response a status code equal to that given
func (o *PostConntrackImportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post conntrack import o k response
func (o *PostConntrackImportOK) Code() int {
	return 200
}

func (o *PostConntrackImportOK) Error() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportOK", 200)
}

func (o *PostConntrackImportOK) String() string {
	return fmt.Sprintf("[POST /conntrack/import][%d] postConntrackImportOK", 200)
}

func (o *PostConntrackImportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
